---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module FinanceDatabaseSpec where

import Database.HaskellDB.DBLayout

import qualified FinanceDatabaseSpec.Quotes
import qualified FinanceDatabaseSpec.Stocks

finance :: DBInfo
finance = DBInfo {dbname = "finance",
                  opts = DBOptions {useBString = True},
                  tbls = [TInfo {tname = "quotes",
                                 cols = [CInfo {cname = "id",
                                                descr = (IntT, False)},
                                         CInfo {cname = "stock_id",
                                                descr = (IntT, False)},
                                         CInfo {cname = "open",
                                                descr = (StringT, False)},
                                         CInfo {cname = "low",
                                                descr = (StringT, False)},
                                         CInfo {cname = "high",
                                                descr = (StringT, False)},
                                         CInfo {cname = "close",
                                                descr = (StringT, False)},
                                         CInfo {cname = "volume",
                                                descr = (IntT, False)},
                                         CInfo {cname = "adj_close",
                                                descr = (StringT, False)}]},
                          TInfo {tname = "stocks",
                                 cols = [CInfo {cname = "id",
                                                descr = (IntT, False)},
                                         CInfo {cname = "shortname",
                                                descr = (BStrT 10, False)},
                                         CInfo {cname = "longname",
                                                descr = (BStrT 100, False)},
                                         CInfo {cname = "exchange_id",
                                                descr = (IntT, False)},
                                         CInfo {cname = "category_id",
                                                descr = (IntT, False)}]}]}